CREATE TABLE Users
(
	id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY,
	login varchar(255) NOT NULL,
	login_lc VARCHAR(255) GENERATED ALWAYS AS (LCASE(login)) NOT NULL,
	pw varchar(255) NOT NULL,
	salt varchar(255) NOT NULL,
	role varchar(20) DEFAULT 'user' NOT NULL,
	reg_ts timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,

	CONSTRAINT uc_login UNIQUE (login),
	CONSTRAINT cc_login_gt0 CHECK(CHARACTER_LENGTH(login) > 0),
	
	CONSTRAINT uc_login_lc UNIQUE (login_lc),
	CONSTRAINT cc_login_lc_gt0 CHECK(CHARACTER_LENGTH(login_lc) > 0),
	CONSTRAINT cc_login_lc_eq_login CHECK(login_lc = LCASE(login)),
	
	CONSTRAINT cc_pw_gt0 CHECK(CHARACTER_LENGTH(pw) > 0),
	CONSTRAINT cc_salt_gt0 CHECK(CHARACTER_LENGTH(salt) > 0)
);
